/**
 * Step 44 — Setup-wizard E2E for AncestryDNA (ADNA-11; Plan §13.1).
 *
 * Drives the full first-run wizard against an AncestryDNA raw-data upload,
 * parameterised by the installed `vep_bundle.version`:
 *
 *   1. **Happy path (bundle v2.0.0 already installed)** — user walks the
 *      wizard, drops an AncestryDNA `.txt` on the Upload step, sees the
 *      "Sample Uploaded" summary with `ancestrydna_v2.0` as the parsed
 *      `file_format`, clicks "Go to Dashboard" and lands on `/` with the
 *      fresh-install gate cleared (`needs_setup=false`).
 *
 *   2. **Pre-v2.0.0 bundle gate** — same wizard walk, but the first
 *      `POST /api/ingest` returns HTTP 409 with the Plan §5.4
 *      `bundle_version_too_old` payload. The Upload step renders the
 *      in-wizard banner with the installed/required versions and the
 *      manifest `update_url`. Clicking the update CTA fires
 *      `POST /api/updates/trigger` for `vep_bundle`, the mocked job
 *      reports `complete` on the first poll, the banner clears, and a
 *      second `POST /api/ingest` (replayed by the user) succeeds with
 *      202 + `ancestrydna_v2.0`.
 *
 * Every backend endpoint is intercepted with `page.route()` so the spec
 * stays deterministic across Chromium / Firefox / WebKit without touching
 * the real ingest pipeline or the ~600 MB VEP bundle. Patterned after
 * `setup-wizard-lai.spec.ts` (Step 32) and `lai-ancestrydna.spec.ts`
 * (Step 25).
 */

import { expect, test, type Page } from '@playwright/test'

// ── Fixture data ────────────────────────────────────────────────────────

const SAMPLE_ID = 1
const JOB_ID = 'job-ingest-ancestrydna'
const BUNDLE_JOB_ID = 'job-bundle-update'

const SETUP_BASE = {
  disclaimer_accepted: true, // skip the disclaimer step in the wizard
  data_dir: '/tmp/.yeliztli',
}

const ANCESTRYDNA_HEAD = [
  '#AncestryDNA raw data download',
  '#This file was generated by AncestryDNA',
  '# AncestryDNA array version: V2.0',
  '#This raw data file may be used for personal or research purposes.',
  '#Below is a text version of your data. Fields are TAB-separated.',
  '#Each line corresponds to a single SNP. For each SNP, we provide its identifier',
  '#(an rsid or an internal id), its location on a reference human assembly',
  '#(chromosome and position), and the two alleles observed at this position.',
  'rsid\tchromosome\tposition\tallele1\tallele2',
  'rs4477212\t1\t82154\tA\tA',
  'rs3094315\t1\t752566\tA\tG',
  '',
].join('\n')

const ANCESTRYDNA_FILE = {
  name: 'AncestryDNA.txt',
  mimeType: 'text/plain',
  buffer: Buffer.from(ANCESTRYDNA_HEAD, 'utf8'),
}

const INGEST_SUCCESS = {
  sample_id: SAMPLE_ID,
  job_id: JOB_ID,
  variant_count: 589,
  nocall_count: 4,
  file_format: 'ancestrydna_v2.0',
}

const BUNDLE_GATE_PAYLOAD = {
  error: 'bundle_version_too_old',
  installed_version: 'v1.0.0',
  required_version: 'v2.0.0',
  vendor: 'ancestrydna',
  update_url:
    'https://github.com/example/yeliztli/releases/download/bundle-v2.0.0/vep_bundle.db',
  size_bytes: 612_345_678,
  checksum_sha256: 'b'.repeat(64),
}

const ANCESTRYDNA_SAMPLE = {
  id: SAMPLE_ID,
  name: 'AncestryDNA E2E Sample',
  file_format: 'ancestrydna_v2.0',
  file_hash: 'a'.repeat(64),
  variant_count: INGEST_SUCCESS.variant_count,
  date_collected: '2026-05-20',
  notes: '',
  source: 'AncestryDNA',
  individual_id: null,
  status: 'complete',
  created_at: '2026-05-20T00:00:00Z',
  extra: {},
}

const APP_UPDATE_RESPONSE = {
  update_available: false,
  current_version: '0.2.0',
  latest_version: null,
  release_url: null,
  release_notes: null,
  error: null,
}

const DB_LIST_READY = {
  databases: [
    {
      name: 'clinvar',
      display_name: 'ClinVar',
      description: 'Clinical variant interpretations from NCBI ClinVar',
      filename: 'clinvar.db',
      expected_size_bytes: 250_000_000,
      required: true,
      phase: 1,
      downloaded: true,
      file_size_bytes: 250_000_000,
      build_mode: 'pipeline',
    },
    {
      name: 'gnomad',
      display_name: 'gnomAD',
      description: 'Population allele frequencies',
      filename: 'gnomad_af.db',
      expected_size_bytes: 2_000_000_000,
      required: true,
      phase: 2,
      downloaded: true,
      file_size_bytes: 2_000_000_000,
      build_mode: 'pipeline',
    },
    {
      name: 'vep_bundle',
      display_name: 'VEP Bundle',
      description: 'Pre-computed VEP annotations for 23andMe + AncestryDNA rsID catalogs.',
      filename: 'vep_bundle.db',
      expected_size_bytes: 600_000_000,
      required: true,
      phase: 2,
      downloaded: true,
      file_size_bytes: 600_000_000,
      build_mode: 'download',
    },
    {
      name: 'lai_bundle',
      display_name: 'LAI Bundle (Chromosome Painting)',
      description: 'Local ancestry inference models for chromosome-level ancestry painting.',
      filename: 'lai_bundle.tar.gz',
      expected_size_bytes: 500_000_000,
      required: false,
      phase: 3,
      downloaded: true,
      file_size_bytes: 500_000_000,
      build_mode: 'download',
    },
  ],
  total_size_bytes: 3_350_000_000,
  downloaded_count: 4,
  total_count: 4,
}

// ── Shared route registry ───────────────────────────────────────────────

interface WizardState {
  /**
   * Tracks whether the user has completed the upload step. Flipped to
   * `true` from inside the `/api/ingest` 202 handler so the next
   * `/api/setup/status` poll reports `needs_setup=false` and the
   * AuthGuard no longer redirects `/` back to `/setup`.
   */
  uploaded: boolean
}

async function setupWizardRoutes(page: Page, state: WizardState): Promise<void> {
  await page.route('**/api/auth/status', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        auth_enabled: false,
        has_password: false,
        authenticated: true,
      }),
    })
  })

  await page.route('**/api/setup/status', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        ...SETUP_BASE,
        needs_setup: !state.uploaded,
        has_databases: true,
        has_samples: state.uploaded,
      }),
    })
  })

  await page.route('**/api/setup/disclaimer', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        title: 'Disclaimer',
        text: 'For research / educational use only.',
        accept_label: 'I Understand and Accept',
      }),
    })
  })

  await page.route('**/api/setup/detect-existing', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        existing_found: false,
        has_config: false,
        has_samples: false,
        has_databases: false,
        data_dir: SETUP_BASE.data_dir,
      }),
    })
  })

  await page.route('**/api/setup/storage-info', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        data_dir: SETUP_BASE.data_dir,
        free_space_bytes: 100_000_000_000,
        free_space_gb: 100,
        total_space_bytes: 500_000_000_000,
        total_space_gb: 500,
        status: 'ok',
        message: 'Storage looks good.',
        path_exists: true,
        path_writable: true,
      }),
    })
  })

  await page.route('**/api/setup/set-storage-path', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        success: true,
        data_dir: SETUP_BASE.data_dir,
        free_space_gb: 100,
        status: 'ok',
        message: 'Storage path saved.',
      }),
    })
  })

  await page.route('**/api/setup/credentials', async (route) => {
    if (route.request().method() === 'POST') {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ success: true, message: 'Saved.' }),
      })
      return
    }
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        pubmed_email: '',
        ncbi_api_key: '',
        omim_api_key: '',
      }),
    })
  })

  // All required DBs are already downloaded — the Databases step renders
  // its Continue button enabled without firing /api/databases/download.
  await page.route('**/api/databases', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify(DB_LIST_READY),
    })
  })

  // Samples list flips after upload so the Dashboard can find one matching
  // by ?sample_id=… (the Upload step navigates to `/` with no query string,
  // so the empty-list branch is fine here too).
  await page.route('**/api/samples', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify(state.uploaded ? [ANCESTRYDNA_SAMPLE] : []),
    })
  })

  // Dashboard / app-shell quiet-mocks.
  await page.route('**/api/updates/app-update', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify(APP_UPDATE_RESPONSE),
    })
  })

  await page.route('**/api/updates/prompts**', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify([]),
    })
  })

  await page.route('**/api/updates/status', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify([]),
    })
  })
}

async function walkWizardToUpload(page: Page): Promise<void> {
  await page.goto('/setup')
  await page.waitForLoadState('domcontentloaded')

  // Step 1 — Import from backup → "Skip — Start Fresh"
  await page.getByRole('button', { name: /Skip — Start Fresh/i }).click()

  // Step 2 — Storage → Continue
  await expect(page.getByRole('heading', { name: /Storage Location/i })).toBeVisible()
  await page.getByRole('button', { name: 'Continue' }).click()

  // Step 3 — Credentials → fill required PubMed email + Continue
  await expect(page.getByRole('heading', { name: 'External Services' })).toBeVisible()
  await page.getByLabel(/PubMed email address/i).fill('e2e@example.com')
  await page.getByRole('button', { name: 'Continue' }).click()

  // Step 4 — Databases (all required already downloaded) → Continue
  await expect(page.getByRole('heading', { name: /Reference Databases/i })).toBeVisible()
  await page.getByRole('button', { name: 'Continue' }).click()

  // Step 5 — Upload step is now the active panel.
  await expect(page.getByRole('heading', { name: 'Upload Sample' })).toBeVisible()
}

async function dropAncestryDNAFile(page: Page): Promise<void> {
  // The drop zone hides its <input type="file"> via CSS, but Playwright's
  // setInputFiles works directly on the element regardless of visibility.
  await page.locator('input[type="file"]').setInputFiles(ANCESTRYDNA_FILE)
  await expect(page.getByText(ANCESTRYDNA_FILE.name)).toBeVisible()
}

// ── Specs ───────────────────────────────────────────────────────────────

test.describe('Step 44 — Setup wizard AncestryDNA E2E', () => {
  test('happy path: AncestryDNA upload completes and routes to Dashboard', async ({
    page,
  }) => {
    const state: WizardState = { uploaded: false }
    const ingestRequests: { contentType: string }[] = []

    await setupWizardRoutes(page, state)

    await page.route('**/api/ingest', async (route) => {
      const request = route.request()
      ingestRequests.push({
        contentType: request.headers()['content-type'] ?? '',
      })
      // Flip needs_setup=false on the backend mock the moment a successful
      // upload lands — mirrors production where a stored sample makes
      // setup-status no longer require the wizard. The wizard's
      // setupStatus query is invalidated by `useIngestFile.onSuccess`, so
      // the next refetch picks this up and auto-redirects to `/`.
      state.uploaded = true
      await route.fulfill({
        status: 202,
        contentType: 'application/json',
        body: JSON.stringify(INGEST_SUCCESS),
      })
    })

    await walkWizardToUpload(page)
    await dropAncestryDNAFile(page)
    await page.getByRole('button', { name: 'Upload & Parse' }).click()

    // The wizard auto-navigates to `/` once setupStatus refetches and
    // reports needs_setup=false. Dashboard renders the no-active-sample
    // "Get Started" branch with the page-level "Dashboard" heading.
    await page.waitForURL((url) => url.pathname === '/', { timeout: 15_000 })
    await expect(page.getByRole('heading', { name: 'Dashboard' })).toBeVisible({
      timeout: 10_000,
    })

    expect(ingestRequests).toHaveLength(1)
    expect(ingestRequests[0].contentType).toContain('multipart/form-data')
  })

  test('pre-v2.0.0 bundle gate: 409 banner → update CTA → retry succeeds', async ({
    page,
  }) => {
    type BundleVersion = 'v1.0.0' | 'v2.0.0'
    const state: WizardState = { uploaded: false }
    let bundleVersion: BundleVersion = 'v1.0.0'
    const ingestRequests: { bundleVersion: BundleVersion }[] = []
    const triggerCalls: Array<Record<string, unknown>> = []
    let jobPolls = 0

    await setupWizardRoutes(page, state)

    // /api/ingest flips with the (mocked) installed bundle version: pre-v2
    // returns the Plan §5.4 409 payload; v2 returns 202 and flips
    // needs_setup so the wizard auto-redirects to Dashboard.
    await page.route('**/api/ingest', async (route) => {
      const currentBundleVersion: BundleVersion = bundleVersion
      ingestRequests.push({ bundleVersion: currentBundleVersion })
      if (currentBundleVersion === 'v1.0.0') {
        await route.fulfill({
          status: 409,
          contentType: 'application/json',
          body: JSON.stringify({ detail: BUNDLE_GATE_PAYLOAD }),
        })
        return
      }
      state.uploaded = true
      await route.fulfill({
        status: 202,
        contentType: 'application/json',
        body: JSON.stringify(INGEST_SUCCESS),
      })
    })

    // Bundle-update trigger + job poll. The job reports `complete` on the
    // first poll so `pollJobUntilDone` resolves immediately (no real sleep
    // in the CI clock). When the job completes we flip the mocked installed
    // bundle to v2.0.0 so the user's retry upload returns 202.
    await page.route('**/api/updates/trigger', async (route) => {
      const body = JSON.parse(route.request().postData() ?? '{}')
      triggerCalls.push(body)
      await route.fulfill({
        status: 202,
        contentType: 'application/json',
        body: JSON.stringify({
          job_id: BUNDLE_JOB_ID,
          db_name: 'vep_bundle',
          message: 'Update queued.',
        }),
      })
    })

    await page.route(`**/api/updates/job/${BUNDLE_JOB_ID}`, async (route) => {
      jobPolls += 1
      bundleVersion = 'v2.0.0'
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          job_id: BUNDLE_JOB_ID,
          status: 'complete',
          progress_pct: 100,
          message: 'VEP bundle updated to v2.0.0.',
          error: null,
        }),
      })
    })

    await walkWizardToUpload(page)
    await dropAncestryDNAFile(page)
    await page.getByRole('button', { name: 'Upload & Parse' }).click()

    // Banner renders the Plan §5.4 payload: installed + required versions
    // and the manifest update URL's ~MB size hint.
    const banner = page.getByTestId('bundle-gate-banner')
    await expect(banner).toBeVisible({ timeout: 10_000 })
    await expect(banner).toContainText(/Update VEP bundle \(~612 MB\)/i)
    await expect(banner).toContainText(/v2\.0\.0/)
    await expect(banner).toContainText(/v1\.0\.0/)
    expect(ingestRequests).toHaveLength(1)

    // CTA fires POST /api/updates/trigger for vep_bundle; the polled job
    // reports complete; the banner clears and the upload button reappears
    // for the user to retry.
    await page.getByTestId('bundle-gate-update-cta').click()
    await expect(banner).toBeHidden({ timeout: 15_000 })
    expect(triggerCalls).toEqual([{ db_name: 'vep_bundle' }])
    expect(jobPolls).toBeGreaterThan(0)

    // Retry the upload — same selected file, now with bundleVersion='v2.0.0'.
    await page.getByRole('button', { name: 'Upload & Parse' }).click()

    // Same auto-redirect path as the happy-path spec: needs_setup flips
    // false the moment the (now-202) ingest lands, wizard refetches
    // setupStatus, navigates to `/`, Dashboard renders.
    await page.waitForURL((url) => url.pathname === '/', { timeout: 15_000 })
    await expect(page.getByRole('heading', { name: 'Dashboard' })).toBeVisible({
      timeout: 10_000,
    })

    expect(ingestRequests).toHaveLength(2)
    expect(ingestRequests[1].bundleVersion).toBe('v2.0.0')
  })
})
