"""Dispatcher unit tests (ADNA-08b; Plan §8.3).

Covers vendor detection precedence + the rejection-with-guidance surface:

- 23andMe fixtures (v3 / v4 / v5) detect as `TWENTYTHREEANDME`.
- AncestryDNA fixture detects as `ANCESTRYDNA`; an uncommented 5-column
  header alone (no `#AncestryDNA` comment) also detects as `ANCESTRYDNA`.
- A file carrying BOTH signatures routes to 23andMe (precedence rule).
- Unknown / empty / binary / comment-only / VCF / CSV inputs raise
  `UnsupportedFormatError` with the matching guidance message.
- `dispatcher.parse()` on a real 23andMe v5 fixture returns the unified
  `base.ParseResult` shape (vendor + string version + build + variants).
"""

from __future__ import annotations

import io
from pathlib import Path

import pytest

from backend.ingestion import dispatcher
from backend.ingestion.base import (
    ParsedVariant,
    ParseResult,
    SourceVendor,
    UnsupportedFormatError,
)

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures"


# --------------------------------------------------------------------------- #
# Positive detection                                                          #
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize(
    "filename",
    ["sample_23andme_v3.txt", "sample_23andme_v4.txt", "sample_23andme_v5.txt"],
)
def test_detect_vendor_23andme_fixtures(filename: str) -> None:
    assert dispatcher.detect_vendor(FIXTURES / filename) == SourceVendor.TWENTYTHREEANDME


def test_detect_vendor_ancestrydna_fixture() -> None:
    vendor = dispatcher.detect_vendor(FIXTURES / "sample_ancestrydna_v2.txt")
    assert vendor == SourceVendor.ANCESTRYDNA


def test_detect_ancestrydna_via_uncommented_header_only() -> None:
    """An uncommented 5-column header alone identifies AncestryDNA per Plan §8.3."""
    stream = io.StringIO("rsid\tchromosome\tposition\tallele1\tallele2\nrs1\t1\t12345\tA\tG\n")
    assert dispatcher.detect_vendor(stream) == SourceVendor.ANCESTRYDNA


def test_detect_23andme_via_header_only() -> None:
    """The canonical 4-column 23andMe header alone identifies 23andMe."""
    stream = io.StringIO("# rsid\tchromosome\tposition\tgenotype\nrs1\t1\t12345\tAT\n")
    assert dispatcher.detect_vendor(stream) == SourceVendor.TWENTYTHREEANDME


# --------------------------------------------------------------------------- #
# Precedence (ambiguous file with both signatures)                            #
# --------------------------------------------------------------------------- #


def test_ambiguous_both_signatures_route_to_23andme() -> None:
    """When both signatures appear, 23andMe wins (Plan §8.3 precedence)."""
    stream = io.StringIO(
        "# This data file generated by 23andMe at: Tue Jan 14 2025\n"
        "#AncestryDNA mention in a comment\n"
        "# rsid\tchromosome\tposition\tgenotype\n"
        "rs1\t1\t12345\tAT\n"
    )
    assert dispatcher.detect_vendor(stream) == SourceVendor.TWENTYTHREEANDME


# --------------------------------------------------------------------------- #
# Rejection with guidance                                                     #
# --------------------------------------------------------------------------- #


def test_vcf_rejected_with_vcf_message() -> None:
    fixture = FIXTURES / "sample_not_23andme.vcf"
    assert fixture.exists(), "sample_not_23andme.vcf fixture must exist"
    with pytest.raises(UnsupportedFormatError, match="VCF"):
        dispatcher.detect_vendor(fixture)


def test_csv_rejected_with_csv_message(tmp_path: Path) -> None:
    p = tmp_path / "random.csv"
    p.write_text("name,age,city\nAlice,30,NYC\nBob,25,LA\nCharlie,42,SF\n")
    with pytest.raises(UnsupportedFormatError, match="comma-separated"):
        dispatcher.detect_vendor(p)


def test_unknown_text_rejected_with_generic_message() -> None:
    stream = io.StringIO("hello world\nfoo bar baz\nthis is not a genotype file\n")
    with pytest.raises(UnsupportedFormatError, match="Unrecognized file format"):
        dispatcher.detect_vendor(stream)


def test_empty_file_rejected(tmp_path: Path) -> None:
    p = tmp_path / "empty.txt"
    p.write_text("")
    with pytest.raises(UnsupportedFormatError, match="Unrecognized file format"):
        dispatcher.detect_vendor(p)


def test_binary_file_rejected_with_binary_message(tmp_path: Path) -> None:
    p = tmp_path / "binary.bin"
    p.write_bytes(b"\x00\x01\x02\x03binary garbage\xff\xfe")
    with pytest.raises(UnsupportedFormatError, match="binary"):
        dispatcher.detect_vendor(p)


def test_comment_only_file_rejected() -> None:
    """A file with only comment lines and no vendor signature is unknown."""
    stream = io.StringIO("# just a comment\n# another comment\n# and one more\n")
    with pytest.raises(UnsupportedFormatError, match="Unrecognized file format"):
        dispatcher.detect_vendor(stream)


def test_non_seekable_stream_rejected() -> None:
    """Detection requires a seekable stream so the head read can rewind."""

    class _NonSeekable(io.StringIO):
        def seekable(self) -> bool:  # type: ignore[override]
            return False

    with pytest.raises(ValueError, match="seekable"):
        dispatcher.detect_vendor(_NonSeekable("# rsid\tchromosome\tposition\tgenotype\n"))


# --------------------------------------------------------------------------- #
# parse() — routing + unified ParseResult shape                               #
# --------------------------------------------------------------------------- #


def test_parse_23andme_v5_returns_unified_result() -> None:
    result = dispatcher.parse(FIXTURES / "sample_23andme_v5.txt")
    assert isinstance(result, ParseResult)
    assert result.vendor == SourceVendor.TWENTYTHREEANDME
    assert result.version == "v5"
    assert isinstance(result.version, str)
    assert result.build == "GRCh37"
    assert len(result.variants) > 0
    assert all(isinstance(v, ParsedVariant) for v in result.variants)
    # Sanity: composed file_format per Plan §8.7.
    assert f"{result.vendor.value}_{result.version}" == "23andme_v5"
